<?php

namespace AppBundle\Repository;

/**
 * culinairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class culinairesRepository extends \Doctrine\ORM\EntityRepository
{
}
