<?php

namespace AppBundle\Repository;

/**
 * definationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class definationsRepository extends \Doctrine\ORM\EntityRepository
{
}
