<?php

namespace AppBundle\Repository;

/**
 * filmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filmRepository extends \Doctrine\ORM\EntityRepository
{
}
