<?php

namespace AppBundle\Repository;

/**
 * guessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class guessRepository extends \Doctrine\ORM\EntityRepository
{
}
