<?php

namespace AppBundle\Repository;

/**
 * informatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
