<?php

namespace AppBundle\Repository;

/**
 * jeuxsocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jeuxsocialRepository extends \Doctrine\ORM\EntityRepository
{
}
