<?php

namespace AppBundle\Repository;

/**
 * SerialtvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialtvRepository extends \Doctrine\ORM\EntityRepository
{
}
