<?php

namespace AppBundle\Repository;

/**
 * siglesfrancaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class siglesfrancaisRepository extends \Doctrine\ORM\EntityRepository
{
}
